### ISSUE TITLE
The lab Page still is giving me errors

### ISSUE THREAD

**Issue by sup-Udh** [ErrNotFound-org/dosis#1]
@Bobby3105  The lab page is still giving me errors when i try to redirect it Please look it into in and yeah Please make a logout button on the doctor and the user page thanks!

**Comment by akshithio** [comment]
Logout button will do, but what's the errors, I'll have to check with auth at this rate 😅

**Comment by akshithio** [comment]
Ok got it, I'll push the fix on the next commit along with the completed blog UI + the rest of the doctor UI, you'll need to auth lock the blog and blog/create page

**Comment by sup-Udh** [comment]
yeah alright, push and then lemme know

**Comment by akshithio** [comment]
Fixed in vsc live ;)
